spring:
  application:
    name: knownact-user
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.29.205:3306/knownact
    username: root
    password: DavidLiu7
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.31.212:8849
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 123.57.29.205
    database: 0
    password: DavidLiu7
server:
  port: 8081
  servlet:
    context-path: /api/user
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)